
on: push
name: Docker Image CI

jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: build and push to docker
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: "camilopez/prueba"
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}

  build:
    name: Build, Push and Release a Docker container to Heroku. # Your custom step name
      runs-on: ubuntu-latest
      needs: build-and-push
      uses: gonuit/heroku-docker-deploy@v1.3.3 # GitHub action name (leave it as it is).
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "prueba-camilo-lopez"
          
          
