name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    name: build and push image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build and push to docker
      uses: docker/prueba@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}
  build:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
    - uses: actions/checkout@Agregado-a-docker-hub
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag prueba:$(date +%s) 
    - uses: camilo-lopez/prueba@v3.12.12 # This is the action
      with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "prueba-camilo-lopez" #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}} 
